DROP TABLE IF EXISTS `db_tp`.`Usuario` ;
DROP TABLE IF EXISTS `db_tp`.`Retiro` ;
DROP TABLE IF EXISTS `db_tp`.`Bicicleta` ;
DROP TABLE IF EXISTS `db_tp`.`Estacion` ;
DROP TABLE IF EXISTS `db_tp`.`Barrio` ;

-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 18:18:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tp` DEFAULT CHARACTER SET utf8 ;
USE `db_tp` ;

-- -----------------------------------------------------
-- Table `db_tp`.`Barrio`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_tp`.`Barrio` (
  `barrio_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`barrio_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `barrio_id_UNIQUE` (`barrio_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `db_tp`.`Estacion`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `db_tp`.`Estacion` (
  `estacion_id` INT NOT NULL AUTO_INCREMENT,
  `barrio_id` INT NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`estacion_id`),
  INDEX `barrio_id_idx` (`barrio_id` ASC) VISIBLE,
  UNIQUE INDEX `estacion_id_UNIQUE` (`estacion_id` ASC) VISIBLE,
  CONSTRAINT `Barrio-Estacion`
    FOREIGN KEY (`barrio_id`)
    REFERENCES `db_tp`.`Barrio` (`barrio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tp`.`Bicicleta`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_tp`.`Bicicleta` (
  `bicicleta_id` INT NOT NULL AUTO_INCREMENT,
  `bici_codigo` VARCHAR(6) NOT NULL,
  `estacion_id` INT NULL,
  PRIMARY KEY (`bicicleta_id`),
  UNIQUE INDEX `bici_codigo_UNIQUE` (`bici_codigo` ASC) VISIBLE,
  INDEX `estacion_id_idx` (`estacion_id` ASC) VISIBLE,
  UNIQUE INDEX `bicicleta_id_UNIQUE` (`bicicleta_id` ASC) VISIBLE,
  CONSTRAINT `Estacion-Bicicleta`
    FOREIGN KEY (`estacion_id`)
    REFERENCES `db_tp`.`Estacion` (`estacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tp`.`Usuario`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_tp`.`Usuario` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `deudaActual` INT NULL DEFAULT 0,
  `deudaHistorica` INT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tp`.`Retiro`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `db_tp`.`Retiro` (
  `user_id` INT NOT NULL,
  `bici_id` INT NOT NULL,
  `time_start` DATETIME NOT NULL,
  `estacion_start` INT NOT NULL,
  `time_end` DATETIME NULL,
  `estacion_end` INT NULL,
  PRIMARY KEY (`user_id`, `bici_id`, `time_start`),
  INDEX `estacion_id_idx` (`estacion_start` ASC, `estacion_end` ASC) VISIBLE,
  INDEX `bici_id_idx` (`bici_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Retiro-Estacion1`
    FOREIGN KEY (`estacion_start`)
    REFERENCES `db_tp`.`Estacion` (`estacion_id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Retiro-Estacion2`
    FOREIGN KEY (`estacion_end`)
    REFERENCES `db_tp`.`Estacion` (`estacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Retiro-Bicicleta`
    FOREIGN KEY (`bici_id`)
    REFERENCES `db_tp`.`Bicicleta` (`bicicleta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Retiro-Usuario`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_tp`.`Usuario` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- levantar mysql server -> sam apache mysql https://www.apachefriends.org/es/download.html -> genera bdd, user, pass, tables
-- mysql workbench motor server 
-- express guia + installs https://expressjs.com/es/guide/database-integration.html

-- e

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'contraseña12345';

FLUSH PRIVILEGES;
